#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# goes to the backend directory, to run the linter
cd back-end
npm run lint:fix

# go back to the root directory then go into the front-end directory, to run the linter
cd ../front-end
npm run lint:fix